### ISSUE TITLE
Error - OSError: [Errno 5] EIO

### ISSUE THREAD

**Issue by graham-mitchell-vcs** [CoreElectronics/CE-PiicoDev-MPU6050-MicroPython-Module#1]
As noted in https://forum.core-electronics.com.au/t/piicodev-mpu-6050-motion-sensor-error/10695/3

The OP added a delay which worked, though the error occurs on large senser values.

Code used:

```
from PiicoDev_MPU6050 import PiicoDev_MPU6050 # calls PiicoDev_Unified.py

from time import sleep

motion = PiicoDev_MPU6050()
sleep(0.5)
while True:
    
    accel = motion.read_accel_data() # read the accelerometer [ms^-2]
    aX = accel["x"]
    aY = accel["y"]
    aZ = accel["z"]
    print("Accelerometer data - ")
    print("x:" + str(aX) + " y:" + str(aY) + " z:" + str(aZ))
    
    sleep(1.5)```

*The [ms^-2] does not appear in Thonny.*

*And this is the result when I shake the sensor* -

Accelerometer data - 
x:-0.4381389 y:-0.02394202 z:9.636662
Accelerometer data - Good News.
x:1.422156 y:0.3280056 z:9.40203
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "PiicoDev_MPU6050.py", line 128, in read_accel_data
  File "PiicoDev_MPU6050.py", line 105, in get_accel_range
  File "PiicoDev_Unified.py", line 104, in read16
  File "PiicoDev_Unified.py", line 115, in UnifiedRead
OSError: [Errno 5] EIO
>>> 
*I wonder if the accel or ax ay az vars are not holding the larger result?*

*The other consideration is that the purpose is to detect someone moving my eBike to steal it.  Maybe I should be using the Gforce or gyroscope data.  I will give them a try.*
```

**Comment by graham-mitchell-vcs** [comment]
The issue seems to have been isolated to the connector https://forum.core-electronics.com.au/t/piicodev-mpu-6050-motion-sensor-error/10695/9?u=graham

Given the nature of this device (motion sensor) - let's consider adding 3-5 reattempts to initialise before passing the error through and failing. Not infinite, as it may have undesired outcomes for the majority of users. 

Thoughts?

**Comment by CoreProduction** [comment]
I'll also roll in a small delay, as pointed out by another user.

**Comment by CoreProduction** [comment]
@CoreProduction2 Let's handle comms issues by returning `None` from device modules. Here's some pseudocode for the temperature sensor as an example.

**User code**
```python
tempC = tempSensor.getTempC()
```

**Device module**
```python
def readTempC(self):
    try:
        data = self.i2c.read16(self.addr, REG_TEMPC)
    except:
        print("PiicoDev could not communicate with module at address {self.addr}, check wiring")
        return None
    
    # proceed with data->temperature conversion and return result
```

Consider loading the print statement into the actual bus-calling function eg `PiicoDev_Unified.py` > `read16` to avoid duplicating the print statement in every device module. Device modules will still need to check for `None` being returned.

**Comment by graham-mitchell-vcs** [comment]
Great, let's go with that as a standard implementation for device drivers.
